In [1]:
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score, recall_score, precision_score

In [2]:
df = pd.read_csv('FinalDataset.csv')

In [3]:
df.describe()

,Unnamed: 0,Length,Subdomain length,Uppercase count,Lowercase count,Numeric count,Entropy,Special Char Count,Max label length,Average label length,Number of Labels,Length of domain,Label
count,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06,2.500000e+06
mean,1.250000e+06,1.272629e+02,5.460806e+01,1.952912e+01,2.608185e+01,1.048254e+01,4.252133e+00,4.752044e+00,1.907786e+01,1.041617e+01,4.636034e+00,2.601465e+00,4.000000e-01
std,7.216880e+05,6.274030e+01,5.811943e+01,2.756463e+01,2.240641e+01,1.264938e+01,9.705079e-01,3.556000e+00,1.510874e+01,7.491732e+00,2.124396e+00,1.156396e+00,4.898980e-01
min,0.000000e+00,6.300000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.916728e-01,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
25%,6.249998e+05,7.900000e+01,1.100000e+01,0.000000e+00,1.300000e+01,0.000000e+00,3.446439e+00,2.000000e+00,8.000000e+00,5.000000e+00,3.000000e+00,2.000000e+00,0.000000e+00
50%,1.250000e+06,9.500000e+01,2.300000e+01,0.000000e+00,1.600000e+01,2.000000e+00,3.873141e+00,4.000000e+00,1.400000e+01,7.666667e+00,4.000000e+00,2.000000e+00,0.000000e+00
75%,1.874999e+06,1.700000e+02,9.200000e+01,3.300000e+01,3.700000e+01,2.100000e+01,5.265979e+00,7.000000e+00,2.300000e+01,1.342857e+01,7.000000e+00,3.000000e+00,1.000000e+00
max,2.499999e+06,1.514000e+03,2.410000e+02,1.220000e+02,2.070000e+02,6.800000e+01,5.933763e+00,8.400000e+01,6.300000e+01,3.471429e+01,4.600000e+01,3.700000e+01,1.000000e+00

In [8]:
df.describe().apply(lambda s: s.apply(lambda x: format(x, 'g')))

,Unnamed: 0,Length,Subdomain length,Uppercase count,Lowercase count,Numeric count,Entropy,Special Char Count,Max label length,Average label length,Number of Labels,Length of domain,Label
count,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06,2.5e+06
mean,1.25e+06,127.263,54.6081,19.5291,26.0819,10.4825,4.25213,4.75204,19.0779,10.4162,4.63603,2.60146,0.4
std,721688,62.7403,58.1194,27.5646,22.4064,12.6494,0.970508,3.556,15.1087,7.49173,2.1244,1.1564,0.489898
min,0,63,0,0,0,0,0.591673,0,1,1,1,1,0
25%,625000,79,11,0,13,0,3.44644,2,8,5,3,2,0
50%,1.25e+06,95,23,0,16,2,3.87314,4,14,7.66667,4,2,0
75%,1.875e+06,170,92,33,37,21,5.26598,7,23,13.4286,7,3,1
max,2.5e+06,1514,241,122,207,68,5.93376,84,63,34.7143,46,37,1

In [5]:
df.head()

,Unnamed: 0,Length,Website,Subdomain length,Uppercase count,Lowercase count,Numeric count,Entropy,Special Char Count,Max label length,Average label length,Number of Labels,Length of domain,Label
0,0,72,lol-porn.com,8,0,10,0,3.022055,2,8,5.500000,2,3,0
1,1,82,ns3-03.azuregov-dns.us,18,0,15,3,3.788755,4,12,6.666667,3,2,0
2,2,69,nsdsp.com,5,0,8,0,2.947703,1,5,4.000000,2,3,0
3,3,74,www.news18.com,9,0,10,2,3.093069,2,6,4.000000,3,3,0
4,4,116,r5---sn-npobuxa-npoy.googlevideo.com,31,0,28,1,4.062305,7,20,11.333333,3,3,0

In [4]:
df.dtypes

Unnamed: 0                int64
Length                    int64
Website                  object
Subdomain length          int64
Uppercase count           int64
Lowercase count           int64
Numeric count             int64
Entropy                 float64
Special Char Count        int64
Max label length          int64
Average label length    float64
Number of Labels          int64
Length of domain          int64
Label                     int64
dtype: object

In [9]:
malicious = df[df['Label'] == 1]
malicious.describe().apply(lambda s: s.apply(lambda x: format(x, 'g')))

,Unnamed: 0,Length,Subdomain length,Uppercase count,Lowercase count,Numeric count,Entropy,Special Char Count,Max label length,Average label length,Number of Labels,Length of domain,Label
count,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06,1e+06
mean,2e+06,191.83,113.079,48.8213,39.8684,24.3288,5.37103,7.81147,32.7165,17.3342,6.75083,2.00001,1
std,288675,51.216,51.0638,21.6669,28.8895,8.44513,0.217319,3.29527,14.7402,7.30709,1.29931,0.00399999,0
min,1.5e+06,72,7,0,0,0,3.25163,1,7,3.19048,2,2,1
25%,1.75e+06,170,91,30,13,19,5.20277,5,23,13.2857,6,2,1
50%,2e+06,170,92,52,40,22,5.34572,8,33,15.5,7,2,1
75%,2.25e+06,178,97,61,46,25,5.45638,10,43,18.8,7,2,1
max,2.5e+06,320,241,122,137,68,5.93376,51,63,34.7143,44,4,1

In [11]:
benign = df[df['Label'] == 0]
benign.describe().apply(lambda s: s.apply(lambda x: format(x, 'g')))

,Unnamed: 0,Length,Subdomain length,Uppercase count,Lowercase count,Numeric count,Entropy,Special Char Count,Max label length,Average label length,Number of Labels,Length of domain,Label
count,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06,1.5e+06
mean,750000,84.2182,15.6273,0.00100533,16.8908,1.25169,3.5062,2.71243,9.98546,5.80414,3.22617,3.00244,0
std,433013,13.4067,9.62773,0.093618,8.3159,2.47177,0.383774,1.85362,5.37847,2.1842,1.19456,1.35159,0
min,0,63,0,0,0,0,0.591673,0,1,1,1,1,0
25%,375000,75,10,0,11,0,3.25163,2,7,4.33333,3,3,0
50%,750000,81,13,0,15,0,3.50689,2,9,5.33333,3,3,0
75%,1.125e+06,93,19,0,21,2,3.7622,3,12,6.85714,4,3,0
max,1.5e+06,1514,216,12,207,57,4.90928,84,63,33.6667,46,37,0

In [5]:
# counting the values for eaach class
#target_names = { 0: 'Not Fraud', 1: 'Fraud'}
#df.Class.value_counts().rename(index = target_names)

Not Fraud    284315
Fraud           492
Name: Class, dtype: int64

In [6]:
# getting the columns for x and y
x_name = df.iloc[:, 1:30].columns
y_name = df.iloc[:1, 30: ].columns

In [7]:
x_name

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount'],
      dtype='object')

In [8]:
y_name

Index(['Class'], dtype='object')

In [9]:
data_x = df[x_name]
data_y = df[y_name]

In [10]:
train_x, test_x, train_y, test_y = train_test_split(data_x, data_y, train_size=0.7, test_size=0.3)

In [13]:
model = LogisticRegression(solver='liblinear')

model.fit(train_x, train_y.values.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
pred_y = model.predict(test_x)

In [15]:
accuracy_score(test_y, pred_y)

0.9991456292499094

In [16]:
f1_score(test_y, pred_y)

0.6572769953051644

In [17]:
precision_score(test_y, pred_y)

0.875

In [18]:
recall_score(test_y, pred_y)

0.5263157894736842

In [19]:
mlflow.sklearn.save_model(model, path='./fraud_model')